services:
  redis:
    image: "redis:5-alpine"
  nginx:
    build:
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - "web"
    volumes:
      - content:/srv/www
  web:
    build: .
    command: python pywsgi.py
    depends_on:
      - "redis"
    volumes:
      - content:/app/output
  worker:
    build: .
    command: poetry run celery -A worker worker -B -l info
    depends_on:
      - "redis"

volumes:
  content:
