services:
  redis:
    image: "redis:5-alpine"
    restart: always
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - "web"
    volumes:
      - content:/app/output
  web:
    build: .
    command: gunicorn -k gevent --access-logfile - -b 0.0.0.0:5000 'app:app'
    restart: always
    depends_on:
      - "redis"
    volumes:
      - content:/app/output/html
  worker:
    build: .
    command: poetry run celery -A worker worker -l debug
    restart: always
    depends_on:
      - "redis"
    volumes:
      - content:/app/output/html

volumes:
  content:
