services:
  redis:
    image: "redis:5-alpine"
  web:
    build: .
    command: poetry run flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
  worker:
    build: .
    command: poetry run celery -A worker worker -B -l info
    depends_on:
      - "redis"

