# Git repository to pull content from
[repository]
# Url to the repository to clone
url = "../rstblog-content"
# Directory to clone into
directory = "./output/repo"

[rst]
# Path to the index page
index = "./index.rst"
# Relative to the repo, location of the folder containing all the pages
pages = "./pages"
# Relative to the repo, location of the folder containing all the posts
posts = "./posts"

[server]
port = 3000
directory = "./output/html"
secret = ""

