# Git repository to pull content from
[repository]
# Url to the repository to clone
url = "../rstblog-content"
# Directory to clone into
directory = "./output/repo"
# Branch to use
branch = "main"

[server]
directory = "./output/html"
secret = ""

